---
apiVersion: kyverno.io/v2beta1
kind: ClusterCleanupPolicy
metadata:
  name: delete-inferenceservice-pod
spec:
  match:
    any:
    - resources:
        kinds:
          - Pod
        selector:
          matchLabels:
            component: "predictor"
  conditions:
    all:
    - key: "{{ time_since('', '{{ target.metadata.creationTimestamp || '{{ time_now() }}' }}', '') }}"
      operator: GreaterThanOrEquals
      value: 3h
    - key: "{{ target.metadata.namespace }}"
      operator: AnyNotIn
      value:
        - "openshift-*" # add more namespace if needed
        - "llm-hosting"
        - "rhoai-bu-services"
        - "cert-manager*"
        - "kube-*"
        - "knative*"
        - "istio-system"
        - "image-generation"
        - "nvidia-gpu-operator"
        - "redhat-ods-*"
        - "rhods-notebooks"
        - "*-operator"
  schedule: "*/5 * * * *"
