---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: report-deployments-for-scaling-down
spec:
  validationFailureAction: Audit  # Reporting only, no mutation
  rules:
    - name: report-deployments-if-pod-time-greater-3h
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "The Deployment '{{ request.object.metadata.ownerReferences[0].name }}' should be scaled down as the pod '{{ request.object.metadata.name }}' has been running for more than 3 hours."
        pattern: # just to trigger warning
          metadata:
            labels:
              purpose: production
      preconditions:
        all:
          - key: "{{ request.object.spec.tolerations[].key || ''}}"
            operator: AnyIn
            value:
              - nvidia.com/gpu
          - key: "{{ time_since('', '{{ request.object.metadata.creationTimestamp }}', '') }}"
            operator: GreaterThanOrEquals
            value: 3h
          - key: "{{ request.object.metadata.namespace }}"
            operator: AnyNotIn
            value:
              - "openshift-*"
              - llm-hosting
