---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
  name: kyverno:delete-raycluster
rules:
- apiGroups:
  - ray.io
  resources:
  - RayCluster
  verbs:
  - get
  - list
  - delete
